version: '3.9'
services:
  exchange-rate-api:
    image: exchange-rate-api
    container_name: exchange-rate-api
    build:
      context: ExchangeRateRestApi
    ports:
      - "81:8080"
    networks:
      - postgres

  shop-service:
    image: shop-service
    container_name: shop-service
    build:
      context: shop
    depends_on:
      - database
    ports:
      - "80:8080"
    environment:
      - DATABASE_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
    networks:
      - postgres

  database:
    image: postgres:14.5-alpine
    container_name: database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
      - PGDATA=/db-data/var/lib/postgresql/data/pgdata
    volumes:
      - ./db-init-data:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
        resources:
          limits:
            cpus: '1'
            memory: 4G
    networks:
      - postgres

networks:
  postgres: