version: '3.9'
services:
  exchange-rate-api:
    image: exchange-rate-api
    container_name: exchange-rate-api
    build:
      context: ExchangeRateRestApi
    ports:
      - "81:8080"
    networks:
      - spring-cloud-network

  shop:
    image: shop-server
    container_name: shop
    build:
      context: shop
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/postgres
      - DATABASE_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
    networks:
      - spring-cloud-network

  db:
    image: postgres:14.5-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
      - PGDATA='/var/lib/postgresql/data/pgdata'
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
        resources:
          limits:
            cpus: '1'
            memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "sumskoj01@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

networks:
  spring-cloud-network:
    driver: bridge
  postgres:
    driver: bridge
