version: '3'
services:
  exchange-rate-api:
    image: exchange-rate-api
    container_name: exchange-rate-api
    build:
      context: ExchangeRateRestApi
    ports:
      - "81:8080"
    networks:
      - spring-cloud-network

  shop:
    image: shop-server
    container_name: shop
    build:
      context: shop
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/postgres
      - DATABASE_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
    networks:
      - spring-cloud-network

  db:
    image: postgres
    container_name: database
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://localhost:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres

networks:
  spring-cloud-network:
    driver: bridge
